name: MLOps Pipeline

on:
  push:
    branches: [main]

jobs:
  test-suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run Tests
        run: pytest tests/

  train-and-quantize:
    runs-on: ubuntu-latest
    needs: test-suite
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Train and Quantize
        run: |
          python src/train.py
          python src/quantize.py

  build-and-test-container:
    runs-on: ubuntu-latest
    needs: train-and-quantize
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t mlops-linear .

      - name: Run Docker Container
        run: docker run mlops-linear
